export enum MusicalGenre {
    CLASSICAL,
    COMERCIAL_JAZZ,
    COMERCIAL_LATIN,
    COMERCIAL_ROCK,
    COMERCIAL_POP,
    COMERCIAL_VALLENATO,
    FOLKLORIC,
    AFRO_MUSIC,
    EXPERIMENTAL,
    OTHER
}
