export enum MusicalGenre {
    CLASSICAL,
    COMERCIAL_BALLAD,
    COMERCIAL_JAZZ,
    COMERCIAL_ROCK,
    COMERCIAL_POP,
    COMERCIAL_LATIN,
    COMERCIAL_MEX,
    COMERCIAL_CUMBIA_VALLENATO,
    FOLKLORIC,
    AFRO_MUSIC,
    EXPERIMENTAL,
    OTHER
}
